In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
print(a.shape,b.shape)

(4,) (2, 2)


In [ ]:
c = a.reshape((4,1))
c.shape
c

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
d = a.reshape((2,2,1))